### ISSUE TITLE
Build a concmd plugin for converting MD to concordion-actionable HTML?

### ISSUE THREAD

**Issue by neelsmith** [neelsmith/concmd#11]

**Comment by neelsmith** [comment]
Separate project:  integrate this into concmd 2.0

**Comment by neelsmith** [comment]
done

**Comment by nigelcharman** [comment]
Hi Neel. You might also be interested in the work going on in the concordion-markdown-extension project, where we are looking at using different syntax for the Concordion commands. At the moment, we're still experimenting with different syntaxes on different branches - [master](https://github.com/concordion/concordion-markdown-extension/blob/master/src/test/resources/examples/concordion/markdown/ConcordionExamples.md), [alternateSyntax](https://github.com/concordion/concordion-markdown-extension/blob/alternateSyntax/src/test/resources/examples/concordion/markdown/ConcordionExamples.md), [linkSyntax](https://github.com/concordion/concordion-markdown-extension/blob/linkSyntax/src/test/resources/examples/concordion/markdown/ConcordionExamples.md). 

The alternateSyntax is the most complete at this stage. The linkSyntax hasn't been coded, but I'll be working on this over the next few days.

I'd be keen for your feedback on this, and whether we're both heading in the same direction?

Also you might want to have a look at the Concordion [2.0.0-SNAPSHOT release](https://github.com/concordion/concordion/releases/tag/2.0.0-SNAPSHOT), which now has an example command that you could convert your example tag to.
